
package com.simavirtual.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnWebService", targetNamespace = "http://ws.simavirtual.com/", wsdlLocation = "file:/d:/dev/njava/pruebas/WsSimaCli/src/main/wsdl/UnWebService.wsdl")
public class UnWebService_Service
    extends Service
{

    private final static URL UNWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNWEBSERVICE_EXCEPTION;
    private final static QName UNWEBSERVICE_QNAME = new QName("http://ws.simavirtual.com/", "UnWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/d:/dev/njava/pruebas/WsSimaCli/src/main/wsdl/UnWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNWEBSERVICE_WSDL_LOCATION = url;
        UNWEBSERVICE_EXCEPTION = e;
    }

    public UnWebService_Service() {
        super(__getWsdlLocation(), UNWEBSERVICE_QNAME);
    }

    public UnWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNWEBSERVICE_QNAME, features);
    }

    public UnWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, UNWEBSERVICE_QNAME);
    }

    public UnWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNWEBSERVICE_QNAME, features);
    }

    public UnWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UnWebService
     */
    @WebEndpoint(name = "UnWebServicePort")
    public UnWebService getUnWebServicePort() {
        return super.getPort(new QName("http://ws.simavirtual.com/", "UnWebServicePort"), UnWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnWebService
     */
    @WebEndpoint(name = "UnWebServicePort")
    public UnWebService getUnWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.simavirtual.com/", "UnWebServicePort"), UnWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNWEBSERVICE_EXCEPTION!= null) {
            throw UNWEBSERVICE_EXCEPTION;
        }
        return UNWEBSERVICE_WSDL_LOCATION;
    }

}
